name: article_classification_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
      - mlflow
      - scikit-learn
      - pandas
      - requests
      - beautifulsoup4
      - numpy
      - transformers
      - torch
  - scikit-learn
  - pandas
  - numpy
  - requests
  - beautifulsoup4
  - transformers
  - torch
